# Generated by Django 3.2.25 on 2025-03-25 04:45

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('orb_features', models.JSONField(blank=True, null=True)),
                ('sift_features', models.JSONField(blank=True, null=True)),
                ('blockchain_tx', models.CharField(blank=True, max_length=255, null=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to=apps.images.models.image_upload_path)),
                ('deepfake_label', models.CharField(blank=True, max_length=10, null=True)),
                ('deepfake_confidence', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
